"""create gtfs tables

Revision ID: 7315b987cd8c
Revises: 
Create Date: 2026-06-12 10:21:14.595695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7315b987cd8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('monday', sa.Boolean(), nullable=False),
    sa.Column('tuesday', sa.Boolean(), nullable=False),
    sa.Column('wednesday', sa.Boolean(), nullable=False),
    sa.Column('thursday', sa.Boolean(), nullable=False),
    sa.Column('friday', sa.Boolean(), nullable=False),
    sa.Column('saturday', sa.Boolean(), nullable=False),
    sa.Column('sunday', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('routes',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('agency_id', sa.String(), nullable=True),
    sa.Column('route_short_name', sa.String(), nullable=True),
    sa.Column('route_long_name', sa.String(), nullable=True),
    sa.Column('route_desc', sa.String(), nullable=True),
    sa.Column('route_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('stops',
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('stop_code', sa.String(), nullable=True),
    sa.Column('stop_name', sa.String(), nullable=False),
    sa.Column('stop_lat', sa.Float(), nullable=False),
    sa.Column('stop_lon', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('stop_id')
    )
    op.create_table('trips',
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('trip_headsign', sa.String(), nullable=True),
    sa.Column('direction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['calendar.service_id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_route_id'), ['route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_service_id'), ['service_id'], unique=False)

    op.create_table('stop_times',
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.String(), nullable=True),
    sa.Column('departure_time', sa.String(), nullable=True),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.stop_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.PrimaryKeyConstraint('trip_id', 'stop_sequence')
    )
    with op.batch_alter_table('stop_times', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stop_times_stop_id'), ['stop_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stop_times', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stop_times_stop_id'))

    op.drop_table('stop_times')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_service_id'))
        batch_op.drop_index(batch_op.f('ix_trips_route_id'))

    op.drop_table('trips')
    op.drop_table('stops')
    op.drop_table('routes')
    op.drop_table('calendar')
    # ### end Alembic commands ###
