"""add_document_deleted_at

Revision ID: 2285336e409a
Revises: ea75db94e85f
Create Date: 2026-06-10 11:36:14.701172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2285336e409a'
down_revision: Union[str, None] = 'ea75db94e85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'deleted_at')
    # ### end Alembic commands ###
