"""sync_chat_history_and_providers

Revision ID: ea75db94e85f
Revises: cc7264069e18
Create Date: 2026-06-09 21:40:41.108357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ea75db94e85f'
down_revision: Union[str, None] = 'cc7264069e18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_provider_configs', schema=None) as batch_op:
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('ANTHROPIC', 'OPENAI', 'OLLAMA', 'GEMINI', 'OPENROUTER', 'CUSTOM', name='llmprovider', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_provider_configs', schema=None) as batch_op:
        batch_op.alter_column('provider',
               existing_type=sa.Enum('ANTHROPIC', 'OPENAI', 'OLLAMA', 'GEMINI', 'OPENROUTER', 'CUSTOM', name='llmprovider', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    # ### end Alembic commands ###
